#

name: Run tests with `uv`

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main

jobs:
  uv-test:
    name: Run tests
    runs-on: ubuntu-latest
    environment:
      name: test

    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --all-extras --dev
        # TODO Better to use --locked for author control over versions?
        # run: uv sync --locked --all-extras --dev

      - name: Set up redis-stack for testing
        run: |
          sudo apt install lsb-release curl gpg
          curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
          sudo chmod 644 /usr/share/keyrings/redis-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
          sudo apt update
          sudo apt install redis-stack-server
      
      - name: Start redis-stack-server
        run: |
          sudo systemctl enable redis-stack-server
          sudo systemctl start redis-stack-server

      - name: Run tests with coverage
        run: uv run pytest --cov=atdata --cov-report=xml --cov-report=term

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          # file: ./coverage.xml # Claude hallucination -- fascinating!
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}


#